### PR TITLE
Post create scripts: install gdb & pybind11

### PR DESCRIPTION
**Pull request by metemaddar**

### CODE REVIEW

**Comment by metemaddar** [comment]
:warning: :stop_sign:   Seems it broke some parts. I couldn't reopen the container.

**Comment by metemaddar** [comment]
:warning: It may break some parts. I couldn't open VS-Code properly in remote container for other branches after creating container with these changes.

**Comment by metemaddar** [comment]
Seemed some parts broke when I tried to run debugger for C++.
- Discarded all the changes in the directory
- And did `rebuild container discard cache`

:white_check_mark: and worked.

**Review by majkshkurti — APPROVED** [review]

**Comment by majkshkurti** [comment]
Changed the branch to dev

**Pull request merged**
