### PR TITLE
feat: added storybook and redoc to documentation

### PR DESCRIPTION
**Pull request by Ebubeker**
The theme looks good. Maybe you could have a look at the dark theme, since we do not have a certain design for the dark theme I just based myself around the dark theme of the storybook. The integration of redoc was a bit tricky but I managed to fix it. Storybook had to be added as a iframe since there is no module to embed it otherwise.

### CODE REVIEW

**Comment by Ebubeker** [comment]
api(dark)
api(light)
footer
homePage(dark)
homePage(light)
storybook

**Comment by Ebubeker** [comment]
An example of how you can implement communication between the parent website and the website within an iframe to handle theme changes:

Parent Website (hosting the iframe):

```
html
Copy code
<!DOCTYPE html>
<html>
<head>
  <script>
    function changeTheme(theme) {
      var iframe = document.getElementById('myIframe');
      iframe.contentWindow.postMessage({ theme: theme }, '*');
    }
  </script>
</head>
<body>
  <button onclick="changeTheme('dark')">Switch to Dark Theme</button>
  <button onclick="changeTheme('light')">Switch to Light Theme</button>
  <iframe id="myIframe" src="https://example.com"></iframe>
</body>
</html>
```
Website within the Iframe (https://example.com/):

```
html
Copy code
<!DOCTYPE html>
<html>
<head>
  <script>
    function applyTheme(theme) {
      // Apply theme-specific styles or classes to the elements within the iframe
      // Here's a simple example that changes the background color
      document.body.style.backgroundColor = theme === 'dark' ? '#000000' : '#FFFFFF';
    }

    window.addEventListener('message', function(event) {
      if (event.origin !== 'https://parent-website.com') {
        return;
      }

      if (event.data.theme) {
        applyTheme(event.data.theme);
      }
    });
  </script>
</head>
<body>
  <!-- Website content goes here -->
</body>
</html>
```
In this example, when the user clicks on the "Switch to Dark Theme" or "Switch to Light Theme" buttons on the parent website, the changeTheme function is called. It sends a message to the iframe using the postMessage API, indicating the selected theme.

The website within the iframe listens for messages using the window.addEventListener function. It checks the origin of the message to ensure it's coming from the trusted parent website (replace 'https://parent-website.com' with the actual origin of the parent website). If the message contains a theme value, it calls the applyTheme function to update the theme of the content within the iframe.

This could be a way to fix the issue, but as I said we have to do it when we fix the storybook.

**Comment by majkshkurti** [comment]
@Ebubeker Thanks for the changes. It looks good. 
I was wondering if we can find another approach on implementing this in docusaurus, as the theme is not the only thing that might not work. As I was thinking, we might have problems with the versioning here as the iframe will always fetch the latest. Same goes for the redoc. 
One possible solution to this is including the storybook as a component so it's build alongside docusaurus. Although I don't know about redoc. There might be a way to export that as well.

**Comment by majkshkurti** [comment]
For the dark mode you can use the Plan4Better white logo. 
https://assets.plan4better.de/img/logo/plan4better_white.svg

This is the standard one. 
https://assets.plan4better.de/img/logo/plan4better_standard.svg

We can switch to svg for better resolution.

**Pull request merged**
